<a href="https://colab.research.google.com/github/Luciesprogram/PyTorch/blob/main/tensors_in_torch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
if torch.cuda.is_available():
  print("GPU available")
else:
  print("GPU not available")

GPU not available


## Creating Tensors


###

In [ ]:
# Creating tensors
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using of seed
torch.rand(2,3)

tensor([[0.5187, 0.6627, 0.6771],
        [0.8468, 0.2582, 0.1476]])

In [ ]:
# using manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arrange
print("using arrange -> ", torch.arange(1,10,2))

# using linespace
print("using linespace ->", torch.linspace(1,10,10))

# using eye
print("using eye -> ", torch.eye(3))

# using full
print("using full ->", torch.full((3,3), 5))

using arrange ->  tensor([1, 3, 5, 7, 9])
using linespace -> tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
using eye ->  tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## **Tensor Shapes**

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[          844140800,           839432192, 4607182418800017408],
        [          536870912,           838142464,           841807424]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

## **Tensor Data Types**

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## **Mathematical Operations**

### 1. Scaler operation

In [ ]:
x = torch.rand(2,2)
x


tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])

In [ ]:
# addition
print(x+2)
# subtraction
print(x-2)
# multiplication
print(x*2)
# division
print(x/2)
# int division
print((x*100)//3)
# mod
print(((x*100)//3)%2)
# power
print(x**2)

tensor([[2.1784, 2.8238],
        [2.5557, 2.9770]])
tensor([[-1.8216, -1.1762],
        [-1.4443, -1.0230]])
tensor([[0.3568, 1.6477],
        [1.1115, 1.9540]])
tensor([[0.0892, 0.4119],
        [0.2779, 0.4885]])
tensor([[ 5., 27.],
        [18., 32.]])
tensor([[1., 1.],
        [0., 0.]])
tensor([[0.0318, 0.6787],
        [0.3089, 0.9546]])


## **Element Wise Operations**

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])
tensor([[0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])


In [ ]:
# addition
a+b
#substraction
a-b
# multiplication
a*b
# division
a/b
# power
a**b
# mod
a % b

tensor([[0.3059, 0.0204, 0.1629],
        [0.3641, 0.0250, 0.0359]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9,2.3,3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d) # next nearest interger

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## **Reduction Operation**

In [ ]:
e = torch.randint(size=(2,3),low = 0, high=10,dtype=torch.float32)
e

tensor([[5., 4., 8.],
        [9., 5., 4.]])

In [ ]:
# addtion
torch.sum(e)

# sum along columns
torch.sum(e, dim=0)

# sum along rows
torch.sum(e, dim=1)

# mean
torch.mean(e,dim=0)

tensor([4.5000, 4.0000, 4.0000])

In [ ]:
# median
torch.median(e)

tensor(4.)

In [ ]:
# min, max
torch.min(e),torch.max(e)

(tensor(0.), tensor(8.))

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(2.6394)

In [ ]:
# torch.variance
torch.var(e)

tensor(6.9667)

In [ ]:
# argmax
torch.argmax(e) # postion of max item in list

tensor(0)

In [ ]:
# argmin
torch.argmin(e) # postion of min item in list

tensor(4)

## **Matrix Operations**

In [ ]:
f = torch.randint(size=(2,3), low=-0, high=10)
g = torch.randint(size=(3,2), low=-0, high=10)

print(f)
print(g)

tensor([[5, 3, 8],
        [2, 7, 4]])
tensor([[7, 4],
        [9, 1],
        [3, 3]])


In [ ]:
# matrix multiplication

torch.matmul(f,g)

tensor([[86, 47],
        [89, 27]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose

torch.transpose(f,0,1)

tensor([[5, 2],
        [3, 7],
        [8, 4]])

In [ ]:
f

tensor([[5, 3, 8],
        [2, 7, 4]])

In [ ]:
h = torch.randint(size=(3,3),low=0, high=10, dtype=torch.float32)
h

tensor([[0., 3., 1.],
        [5., 8., 3.],
        [3., 2., 8.]])

In [ ]:
# determinant
torch.det(h)

tensor(-107.0000)

In [ ]:
# intverse
torch.inverse(h)

tensor([[-0.5421,  0.2056, -0.0093],
        [ 0.2897,  0.0280, -0.0467],
        [ 0.1308, -0.0841,  0.1402]])

In [ ]:
i = torch.randint(size=(2,3),low=0, high=10)
j = torch.randint(size=(2,3),low=0, high=10)

print(i)
print(j)

tensor([[3, 2, 0],
        [9, 7, 2]])
tensor([[5, 8, 0],
        [1, 5, 7]])


In [ ]:
# greater then
i>j
# less than
i<j
# equal to
i==j

tensor([[False, False,  True],
        [False, False, False]])

In [ ]:
k = torch.randint(size=(2,3),low=0, high=10,dtype=torch.float32)
k

tensor([[4., 9., 8.],
        [6., 9., 2.]])

In [ ]:
# log
torch.log(k)

tensor([[1.0986, 2.1972, 1.9459],
        [1.6094, 0.0000, 0.6931]])

In [ ]:
# exp exponents
torch.exp(k)

tensor([[2.0086e+01, 8.1031e+03, 1.0966e+03],
        [1.4841e+02, 2.7183e+00, 7.3891e+00]])

In [ ]:
# sqrt square root
torch.sqrt(k)

tensor([[1.7321, 3.0000, 2.6458],
        [2.2361, 1.0000, 1.4142]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9999, 0.9991],
        [0.9933, 0.7311, 0.8808]])

In [ ]:
# softmax
torch.softmax(k, dim=0) # this only supports float value

tensor([[0.1192, 0.5000, 0.9975],
        [0.8808, 0.5000, 0.0025]])

In [ ]:
k

tensor([[4., 9., 8.],
        [6., 9., 2.]])

In [ ]:
# relu
torch.relu(k)

tensor([[4., 9., 8.],
        [6., 9., 2.]])

## **Inplace Operations**

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4473, 0.4990, 0.7151],
        [0.4661, 0.6669, 0.1798]])
tensor([[0.3701, 0.2626, 0.0374],
        [0.0098, 0.9962, 0.7512]])


In [ ]:
m.add_(n)

tensor([[0.8174, 0.7616, 0.7525],
        [0.4759, 1.6632, 0.9310]])

In [ ]:
m

tensor([[0.8174, 0.7616, 0.7525],
        [0.4759, 1.6632, 0.9310]])

In [ ]:
n

tensor([[0.3701, 0.2626, 0.0374],
        [0.0098, 0.9962, 0.7512]])

In [ ]:
torch.relu(m)

tensor([[0.8174, 0.7616, 0.7525],
        [0.4759, 1.6632, 0.9310]])

In [ ]:
m.relu_()

tensor([[0.8174, 0.7616, 0.7525],
        [0.4759, 1.6632, 0.9310]])

## **Copy Tensor**

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.5332, 0.1222, 0.4319],
        [0.2149, 0.2938, 0.8086]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.5332, 0.1222, 0.4319],
        [0.2149, 0.2938, 0.8086]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.1222, 0.4319],
        [0.2149, 0.2938, 0.8086]])

In [ ]:
b

tensor([[0.0000, 0.1222, 0.4319],
        [0.2149, 0.2938, 0.8086]])

In [ ]:
id(a)

139849845055216

In [ ]:
id(b)

139849845055216

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.1222, 0.4319],
        [0.2149, 0.2938, 0.8086]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.1222,  0.4319],
        [ 0.2149,  0.2938,  0.8086]])

In [ ]:
b

tensor([[0.0000, 0.1222, 0.4319],
        [0.2149, 0.2938, 0.8086]])

In [ ]:
id(a)

139849845055216

In [ ]:
id(b)

139848642603808

## **Tensor operations of GPU**

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
device

device(type='cuda')

In [ ]:
# creating tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.2593, 0.6512, 0.4571],
        [0.0128, 0.5352, 0.4152]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a = torch.rand((2,3))
a

tensor([[0.0442, 0.0495, 0.3235],
        [0.0956, 0.9608, 0.0360]])

In [ ]:
 b =a.to(device)

In [ ]:
b + 5

tensor([[5.0442, 5.0495, 5.3235],
        [5.0956, 5.9608, 5.0360]], device='cuda:0')

## **Code to check to compare the time difference on GPU and CPU for matrix multiplication**

In [ ]:
import time

size = 10000 # matrix size

# create a random matrix on cpu
mat_1 = torch.rand((size,size))
mat_2 = torch.rand((size,size))

# Measure time on CPU
start_time = time.time()
result = torch.matmul(mat_1, mat_2)
end_time = time.time()
cpu_time = end_time - start_time

print(f"Time on CPU : {cpu_time: 4f} seconds")


# Moving a random matrix on GPU
matgpu_1 = mat_1.to("cuda")
matgpu_2 = mat_2.to("cuda")

# Measure time on CPU
start_time = time.time()
result_gpu = torch.matmul(matgpu_1, matgpu_2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"Time on GPU : {gpu_time: 4f} seconds")

# Compare Results
print("Speedup (cpu time/gpu time):",cpu_time / gpu_time)

Time on CPU :  15.985819 seconds
Time on GPU :  0.562522 seconds
Speedup (cpu time/gpu time): 28.418113757417704


## **Reshaping Tensors**

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten() # it will bring vector or 2d array into one dimension

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,4,3) # 2 depth, 4 rows, 3 cols
b

tensor([[[0.9302, 0.2664, 0.2434],
         [0.5256, 0.0413, 0.6554],
         [0.3769, 0.1021, 0.4710],
         [0.3663, 0.6353, 0.0057]],

        [[0.4140, 0.6945, 0.7389],
         [0.3757, 0.9296, 0.9245],
         [0.8232, 0.2002, 0.4018],
         [0.7120, 0.1519, 0.3132]]])

In [ ]:
# permute
b.permute(2,0,1) # indexing

tensor([[[0.9302, 0.5256, 0.3769, 0.3663],
         [0.4140, 0.3757, 0.8232, 0.7120]],

        [[0.2664, 0.0413, 0.1021, 0.6353],
         [0.6945, 0.9296, 0.2002, 0.1519]],

        [[0.2434, 0.6554, 0.4710, 0.0057],
         [0.7389, 0.9245, 0.4018, 0.3132]]])

In [ ]:
# unsqueeze # add a dimension at the given position
# image size

c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeeze

d = torch.rand(1,20)
print("Before",d, "\n",d.shape)
print("After", d.squeeze(0), "\n",d.squeeze(0).shape)

Before tensor([[0.3699, 0.7935, 0.0368, 0.0673, 0.5384, 0.9502, 0.9184, 0.3868, 0.3155,
         0.8824, 0.9699, 0.5046, 0.8909, 0.4091, 0.1990, 0.8560, 0.7491, 0.1503,
         0.5718, 0.3362]]) 
 torch.Size([1, 20])
After tensor([0.3699, 0.7935, 0.0368, 0.0673, 0.5384, 0.9502, 0.9184, 0.3868, 0.3155,
        0.8824, 0.9699, 0.5046, 0.8909, 0.4091, 0.1990, 0.8560, 0.7491, 0.1503,
        0.5718, 0.3362]) 
 torch.Size([20])


## **Numpy and PyTorch**

In [ ]:
import numpy as np
import torch

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
# converting tensor to numpy array
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])

In [ ]:
type(c)

numpy.ndarray